# Capstone Team 23 - Temporal Titan

## Total Population in All Metropolitans and Micropolitans 2021
Find out the top N Metropolitans with largest population to determine the interested regions.

In [ ]:
NUMBER_OF_CITY = 15

In [ ]:
import pandas as pd

population_df = pd.read_csv('/content/drive/MyDrive/MADS Capstone Team 23/Data/raw/total_population_2022.csv')

filtered_population_df = population_df[['NAME', 'B01003_001E']]

cleaned_df = filtered_population_df.iloc[1:]

cleaned_df = cleaned_df.astype({
    'NAME': 'str',
    'B01003_001E': 'int64'
})

cleaned_df.rename(columns={'NAME': 'Name', 'B01003_001E': 'Population'}, inplace=True)

cleaned_df.sort_values(by='Population', ascending=False, inplace=True)

cleaned_df = cleaned_df.drop_duplicates()

top15_metro_df = cleaned_df.head(NUMBER_OF_CITY)

top15_metro_df

                                                   Name  Population
841    New York-Newark-Jersey City, NY-NJ-PA Metro Area    19617869
269       Los Angeles-Long Beach-Anaheim, CA Metro Area    12872322
85        Chicago-Naperville-Elgin, IL-IN-WI Metro Area     9442159
626          Dallas-Fort Worth-Arlington, TX Metro Area     7943685
204     Houston-The Woodlands-Sugar Land, TX Metro Area     7340118
1007  Washington-Arlington-Alexandria, DC-VA-MD-WV M...     6373829
870   Philadelphia-Camden-Wilmington, PA-NJ-DE-MD Me...     6241164
542     Atlanta-Sandy Springs-Alpharetta, GA Metro Area     6222908
810   Miami-Fort Lauderdale-Pompano Beach, FL Metro ...     6139340
355                Phoenix-Mesa-Chandler, AZ Metro Area     5015678
572           Boston-Cambridge-Newton, MA-NH Metro Area     4900550
904     Riverside-San Bernardino-Ontario, CA Metro Area     4667558
930       San Francisco-Oakland-Berkeley, CA Metro Area     4579599
122              Detroit-Warren-Dearborn, MI Metro Area     4345761
426              Seattle-Tacoma-Bellevue, WA Metro Area     4034248

In [ ]:
top15_metro_df_copy = top15_metro_df.copy()

top15_metro_df_copy['RegionName'] = ''

for index, row in top15_metro_df_copy.iterrows():
  name_string = row['Name']

  split_1 = name_string.split(',')

  first_part = split_1[0]

  split_2 = first_part.split('-')

  metro_name = split_2[0]

  second_part = split_1[1]

  state_abbrev = second_part[:3]

  region_name = metro_name + ',' + state_abbrev

  top15_metro_df_copy.loc[index, 'RegionName'] = region_name

top15_metro_df = top15_metro_df_copy

top15_metro_df

,Name,Population,RegionName
841,"New York-Newark-Jersey City, NY-NJ-PA Metro Area",19617869,"New York, NY"
269,"Los Angeles-Long Beach-Anaheim, CA Metro Area",12872322,"Los Angeles, CA"
85,"Chicago-Naperville-Elgin, IL-IN-WI Metro Area",9442159,"Chicago, IL"
626,"Dallas-Fort Worth-Arlington, TX Metro Area",7943685,"Dallas, TX"
204,"Houston-The Woodlands-Sugar Land, TX Metro Area",7340118,"Houston, TX"
1007,"Washington-Arlington-Alexandria, DC-VA-MD-WV M...",6373829,"Washington, DC"
870,"Philadelphia-Camden-Wilmington, PA-NJ-DE-MD Me...",6241164,"Philadelphia, PA"
542,"Atlanta-Sandy Springs-Alpharetta, GA Metro Area",6222908,"Atlanta, GA"
810,"Miami-Fort Lauderdale-Pompano Beach, FL Metro ...",6139340,"Miami, FL"
355,"Phoenix-Mesa-Chandler, AZ Metro Area",5015678,"Phoenix, AZ"
572,"Boston-Cambridge-Newton, MA-NH Metro Area",4900550,"Boston, MA"
904,"Riverside-San Bernardino-Ontario, CA Metro Area",4667558,"Riverside, CA"
930,"San Francisco-Oakland-Berkeley, CA Metro Area",4579599,"San Francisco, CA"
122,"Detroit-Warren-Dearborn, MI Metro Area",4345761,"Detroit, MI"
426,"Seattle-Tacoma-Bellevue, WA Metro Area",4034248,"Seattle, WA"

## Zillow Home Value Index for the 15 Metros we will be focusing on

In [ ]:
zhvi_df = pd.read_csv('/content/drive/MyDrive/MADS Capstone Team 23/Data/raw/zhvi_metro.csv')

zhvi_df.head()

merged_df = pd.merge(zhvi_df, top15_metro_df, on='RegionName')

processed_zhvi_df = merged_df.drop(columns=['Name', 'Population'])

processed_zhvi_df = processed_zhvi_df.melt(id_vars=['RegionID', 'SizeRank', 'RegionName', 'RegionType', 'StateName'])

processed_zhvi_df.rename(columns={'variable': 'TimePeriod', 'value': 'ZHVI'}, inplace=True)

processed_zhvi_df['TimePeriod'] = pd.to_datetime(processed_zhvi_df['TimePeriod'])

processed_zhvi_df

,RegionID,SizeRank,RegionName,RegionType,StateName,TimePeriod,ZHVI
0,394913,1,"New York, NY",msa,NY,2000-01-31,2.164934e+05
1,753899,2,"Los Angeles, CA",msa,CA,2000-01-31,2.293383e+05
2,394463,3,"Chicago, IL",msa,IL,2000-01-31,1.541898e+05
3,394514,4,"Dallas, TX",msa,TX,2000-01-31,1.282025e+05
4,394692,5,"Houston, TX",msa,TX,2000-01-31,1.229093e+05
...,...,...,...,...,...,...,...
4390,394976,11,"Phoenix, AZ",msa,AZ,2024-05-31,4.613517e+05
4391,395057,12,"San Francisco, CA",msa,CA,2024-05-31,1.183272e+06
4392,395025,13,"Riverside, CA",msa,CA,2024-05-31,5.847095e+05
4393,394532,14,"Detroit, MI",msa,MI,2024-05-31,2.543251e+05
4394,395078,15,"Seattle, WA",msa,WA,2024-05-31,7.534135e+05

In [ ]:
processed_zhvi_df.to_csv('/content/drive/MyDrive/MADS Capstone Team 23/Data//processed/processed_zhvi_df.csv')

## Prepare the Data for Merging

In [35]:
import pandas as pd

cities = ['New York, NY', 'Los Angeles, CA', 'Chicago, IL', 'Dallas, TX', 'Seattle, WA']

zhvi_df = pd.read_csv('/content/drive/MyDrive/MADS Capstone Team 23/Data/raw/zhvi_metro.csv')

filtered_zhvi_df = zhvi_df[zhvi_df['RegionName'].isin(cities)]

filtered_zhvi_df = filtered_zhvi_df.drop(columns=['RegionID', 'SizeRank', "RegionType", "StateName"])

filtered_zhvi_df["City"] = filtered_zhvi_df["RegionName"].str.split(",").str[0]

filtered_zhvi_df = filtered_zhvi_df.drop(columns=['RegionName'])

In [36]:
processed_zhvi_df = filtered_zhvi_df.melt(id_vars=['City'])
processed_zhvi_df.rename(columns={'variable': 'Date', 'value': 'ZHVI'}, inplace=True)
processed_zhvi_df['Date'] = pd.to_datetime(processed_zhvi_df['Date'])
processed_zhvi_df = processed_zhvi_df[(processed_zhvi_df['Date'] >= '2010-01') & (processed_zhvi_df['Date'] <= '2023-01')]
processed_zhvi_df['Date'] = processed_zhvi_df['Date'].dt.strftime('%Y-%m')

In [41]:
processed_zhvi_df[processed_zhvi_df["City"] == "Chicago"]

         City     Date           ZHVI
602   Chicago  2010-01  201888.606600
607   Chicago  2010-02  201527.551140
612   Chicago  2010-03  200518.003420
617   Chicago  2010-04  200674.643669
622   Chicago  2010-05  200205.154396
...       ...      ...            ...
1357  Chicago  2022-08  300423.033179
1362  Chicago  2022-09  298728.977859
1367  Chicago  2022-10  297366.608656
1372  Chicago  2022-11  296587.572167
1377  Chicago  2022-12  296163.399450

[156 rows x 3 columns]

In [43]:
processed_zhvi_df.to_csv('/content/drive/MyDrive/MADS Capstone Team 23/Data/processed/processed_zhvi_df.csv')